name: C CI

on:
  push:
    branches:
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure make file
      run: |
        make All
        make Clean
